version: '3.1'

services:
  wordpress:
      build:
        context: .
        dockerfile: cent_wp.Dockerfile
      restart: unless-stopped
      ports:
        - 8080:80
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_NAME: wordpress_db
        WORDPRESS_DB_USER: user
        WORDPRESS_DB_PASSWORD: pass
        WORDPRESS_DEBUG: 'true'
        WORDPRESS_DEBUG_LOG: 'true'
        WORDPRESS_DEBUG_DISPLAY: 'false'
        TZ: Asia/Tokyo
      volumes:
        - ../wp_src:/var/www/data
  db:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: wordpress_db
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
        TZ: Asia/Tokyo
      volumes:
        - db:/var/lib/mysql
volumes:
    db:
