version: '3.9'

services:
  wordpress:
      build:
        context: .
        dockerfile: cent_apache_wp.Dockerfile
      container_name: wp_app
      restart: unless-stopped
      tty: true
      ports:
        - 8080:80
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_NAME: wordpress_db
        WORDPRESS_DB_USER: user
        WORDPRESS_DB_PASSWORD: pass
        WORDPRESS_DEBUG: 'true'
        WORDPRESS_DEBUG_LOG: 'true'
        WORDPRESS_DEBUG_DISPLAY: 'false'
        TZ: Asia/Tokyo
      depends_on:
        - db
      volumes:
        - ../src:/var/www/html
      networks:
        - wp_net
  db:
      image: mysql:5.7
      container_name: wp_db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: wordpress_db
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
        MYSQL_ROOT_PASSWORD: pass
        TZ: Asia/Tokyo
      volumes:
        - wp_db_data:/var/lib/mysql
        - ../sql:/usr/tmp/sql
      networks:
        - wp_net
volumes:
  wp_db_data:
networks:
  wp_net:
    driver: bridge
